name: CI

on:
    push:
        branches: [main]
    pull_request:

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

            - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86

            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
              with:
                  node-version-file: .nvmrc
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Typecheck
              run: pnpm typecheck

            - name: Lint
              run: pnpm lint --error-on-warnings

            - name: Test
              env:
                  DATABASE_URL: postgres://ci:ci@localhost:5432/ci
              run: pnpm test

            - name: Build
              run: pnpm build
